window.enterpriseDashboardData = {
  filters: {
    periods: ["Hoje", "7 dias", "30 dias", "Trimestre"],
    channels: ["Todos", "ERP", "E-commerce", "Atacado", "Interno"],
    statuses: ["Todos", "Em processamento", "Aguardando ERP", "Concluído", "Atenção"],
  },
  revenueSeries: [
    { label: "Jan", value: 248 },
    { label: "Fev", value: 286 },
    { label: "Mar", value: 312 },
    { label: "Abr", value: 298 },
    { label: "Mai", value: 354 },
    { label: "Jun", value: 381 },
  ],
  orders: [
    {
      id: "PED-10482",
      customer: "Operação Recife",
      channel: "ERP",
      amount: 42800,
      status: "Em processamento",
      priority: "Alta",
      owner: "Faturamento",
      sla: "2h 40min",
    },
    {
      id: "PED-10491",
      customer: "Loja virtual B2B",
      channel: "E-commerce",
      amount: 18540,
      status: "Aguardando ERP",
      priority: "Média",
      owner: "Integração",
      sla: "46min",
    },
    {
      id: "PED-10504",
      customer: "Carteira atacado",
      channel: "Atacado",
      amount: 61200,
      status: "Concluído",
      priority: "Normal",
      owner: "Expedição",
      sla: "Finalizado",
    },
    {
      id: "ROT-8821",
      customer: "Rotina de estoque",
      channel: "Interno",
      amount: 0,
      status: "Atenção",
      priority: "Alta",
      owner: "Backoffice",
      sla: "Vence hoje",
    },
    {
      id: "PED-10516",
      customer: "Pedido marketplace",
      channel: "E-commerce",
      amount: 9700,
      status: "Em processamento",
      priority: "Normal",
      owner: "Separação",
      sla: "1h 15min",
    },
    {
      id: "PED-10522",
      customer: "Reposição matriz",
      channel: "ERP",
      amount: 33750,
      status: "Concluído",
      priority: "Média",
      owner: "Compras",
      sla: "Finalizado",
    },
  ],
  integrations: [
    {
      system: "ERP TOTVS",
      routine: "Pedidos para faturamento",
      status: "Sincronizado",
      processed: 238,
      latency: "1m 12s",
      health: 98,
    },
    {
      system: "Sapiens",
      routine: "Notas fiscais e estoque",
      status: "Monitorando",
      processed: 146,
      latency: "3m 41s",
      health: 91,
    },
    {
      system: "Gateway financeiro",
      routine: "Baixas e conciliação",
      status: "Atenção",
      processed: 72,
      latency: "12m 04s",
      health: 76,
    },
  ],
  inventory: [
    { sku: "KPI-4482", item: "Margem abaixo da meta", stock: 18, min: 30, coverage: "alto" },
    { sku: "KPI-7710", item: "Prazo médio acima do previsto", stock: 42, min: 65, coverage: "médio" },
    { sku: "KPI-2209", item: "Volume concentrado por canal", stock: 76, min: 50, coverage: "baixo" },
    { sku: "KPI-9051", item: "Pendência financeira crítica", stock: 9, min: 25, coverage: "alto" },
  ],
  reconciliation: [
    { label: "Conciliado", value: 84, color: "good" },
    { label: "Pendente", value: 11, color: "warn" },
    { label: "Divergente", value: 5, color: "bad" },
  ],
  timeline: [
    "Carga de pedidos validada com 238 registros processados.",
    "Integração financeira identificou 5 divergências para revisão.",
    "Painel gerencial destacou 3 indicadores fora da meta.",
    "Fila do ERP normalizada após reprocessamento da rotina fiscal.",
  ],
};
